version: "3.2"
services:
    redis:
        image: redis:alpine
        networks:
            - backend

    minio:
        image: minio/minio:latest
        command: ["server", "/data"]
        networks:
            - backend
        volumes:
            - type: volume
              source: storage
              target: /data
        ports:
            - "9000:9000"
        secrets:
            - source: finca_access_key
              target: access_key
            - source: finca_secret_key
              target: secret_key

    manager:
        image: ehazlett/finca:latest
        command: ["/usr/local/bin/finca", "-D", "manager", "--redis-addr", "redis:6379", "--s3-endpoint", "minio:9000"]
        networks:
            - backend
        ports:
            - "8080:8080"
        secrets:
            - source: finca_access_key
              target: access_key
            - source: finca_secret_key
              target: secret_key

    worker:
        image: ehazlett/finca:latest
        command: ["/usr/local/bin/finca", "-D", "agent", "--redis-addr", "redis:6379"]
        deploy:
            replicas: 1
        networks:
            - backend

networks:
    backend:
        driver: overlay

volumes:
    storage:

secrets:
    finca_access_key:
        external: true
    finca_secret_key:
        external: true
