version: "3.3"
services:
    redis:
        image: redis:alpine
        command: ["redis-server", "/etc/redis.conf"]
        configs:
            - source: redis.conf
              target: /etc/redis.conf
        networks:
            - render

    minio:
        image: minio/minio:latest
        command: ["server", "/data"]
        networks:
            - render
        volumes:
            - type: volume
              source: storage
              target: /data
        ports:
            - "9000:9000"
        secrets:
            - source: finca_access_key
              target: access_key
            - source: finca_secret_key
              target: secret_key

    manager:
        image: ehazlett/finca:latest
        command: ["/usr/local/bin/finca", "-D", "manager", "--redis-addr", "redis:6379", "--s3-endpoint", "minio:9000"]
        networks:
            - render
        ports:
            - "8080:8080"
        secrets:
            - source: finca_access_key
              target: access_key
            - source: finca_secret_key
              target: secret_key

    worker:
        image: ehazlett/finca:latest
        command: ["/usr/local/bin/finca", "-D", "agent", "--redis-addr", "redis:6379"]
        deploy:
            replicas: 2
        networks:
            - render

networks:
    render:
        driver: overlay

volumes:
    storage:

configs:
    redis.conf:
        external: true
secrets:
    finca_access_key:
        external: true
    finca_secret_key:
        external: true
