version: "3.2"
services:
    redis:
        image: redis:alpine
        ports:
            - 6379
        networks:
            - backend

    minio:
        image: minio/minio:latest
        command: ["server", "/data"]
        networks:
            - backend
        volumes:
            - type: volume
              source: storage
              target: /data
        ports:
            - 9000
        secrets:
            - source: finca_access_key
              target: access_key
            - source: finca_secret_key
              target: secret_key

    manager:
        image: ehazlett/finca-manager:latest
        command: ["/usr/local/bin/finca", "-D", "manager", "--redis-addr", "redis:6379", "--s3-endpoint", "minio:9000"]
        networks:
            - backend
        ports:
            - 8080
        secrets:
            - source: finca_access_key
              target: access_key
            - source: finca_secret_key
              target: secret_key

    worker:
        image: ehazlett/finca-agent:latest
        command: ["/usr/local/bin/finca", "-D", "agent", "--manager-url", "http://manager:8080"]
        networks:
            - backend

networks:
    backend:
        driver: overlay

volumes:
    storage:

secrets:
    finca_access_key:
        external: true
    finca_secret_key:
        external: true
